web/app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'
Rails.application.routes.draw do
	mount Sidekiq::Web => '/sidekiq'
	resources :tasks do
		collection do
			get 'tools_list'
			post 'update_tool'
			get 'configure_view'
			post 'update_configurations'
		end
	end
	resources :tags
	resources :permissions
	resources :functionalities
	devise_scope :user do
		root :to => 'users/sessions#new'
	end

	devise_for :users,controllers: {registrations: "users/registrations",omniauth_callbacks: "users/omniauth_callbacks"}
	resources :users do
		collection do
			get :autocomplete_user_name
			post :add
		end
	end
	resources :scaners do
		collection do
			get 'run'
			get 'load_projects'
			get 'load_branches'
			post 'store_bulk_scans'
			get 'list_scan_results'
			get 'severity_results'
			get 'scan_wise_results'
			get 'my_scans'
			get 'start_scan_for_all_repo'
			get 'add_dynamic_scans'
			get 'scans_diff'
			get 'run_truffle'
			get 'download_results'
			post 'change_find_status'
			get 'add_target'
			post 'unschedule'
		end
	end
	resources :findings do
		resources :comments
		resources :uploads do
			collection do 
				get 'download_file'
			end
		end
		resources :tags
		collection do
			get 'details'
			post 'change_status'
			post 'add_new_tag'
			post 'add_tag'
			delete 'delete_file'
			post 'change_false_positive'
			post 'publish_to_jira'
			post 'change_to_not_exploitable'
			get 'next_finding'
			post 'save_tag'
		end
	end
	resources :teams do
		collection do
			get 'fetch_projects'
			get 'list_groups'
			get 'repo_summary'
			get 'export_findings'
			get 'list_corpo_groups'
		end
	end
	resources :repos do
		collection do
			 get 'repo_summary'
			 get 'repo_tool_wise_findings'
			 get 'repo_severity_wise_findings'
			 get 'repo_channel_results'
			 get 'get_team_repos'
			 get 'list_apps'
			 get 'false_positive_finds'
			 delete 'delete_repo_channel_results'
		end
	end
	resources :dashboards do
		collection do
			get 'display'
			get 'static'
			get 'web'
			get 'wordpress'
			get 'mobile'
			get 'network'
		end
	end

	resource :settings do
		collection do
			get 'severity'
			get 'scanner'
			get 'jira'
			get 'gitlab'
			get 'github'
			get 'signup_role'
			get 'get_mail_info'
			get 'get_sender_mail'
			get 'pull_corporate_info'
			post 'update_details'
			post 'update_mail_info'
			post 'update_severities'
		end
	end	
	resources :user_management,:controller => :user_management
	resources :roles
	resources :groups
	resources :functionalities
	resources :analytics do
		collection do
			get :load_charts
			post :save_filters
			get :get_desc_wise
		end
	end
	resources :filters do
		collection do
			get :apply_filter
			post :results
		end
	end
	resources :scan_types
	resources :upload_scans do
		collection do
			post 'save_team'
		end
	end
	resources :alert_notifications do
		collection do
			post 'update_alerts'
		end
	end
	get 'restricted', :to=> 'errors#unauthorized'
	%w( 404 422 500 ).each do |code|
		get code, :to => "errors#show", :code => code
	end

end

web/app/app/views/layouts/_applications.html.erb
<div id="sidebar-wrapper">
	<nav class="navbar navbar-default sidebar fill" role="navigation">
		<%unless Setting.application_mode == AppConstants::UserMode::SINGLE_USER%>
			<div class="list-group panel sidebar fill">
				<a href="#corporate_scans" class="list-group-item list-group-item-info" data-toggle="collapse" data-parent="#MainMenu">Corporate Apps<i class="fa fa-caret-down pull-right"></i></a>
				<div id="corporate_scans">
					<%=link_to "Source Code",list_corpo_groups_teams_path(owner_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::STATIC),class: "list-group-item",id: "corporatestatic"%>
					<%=link_to "Web",list_corpo_groups_teams_path(owner_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::WEB),class: "list-group-item",id: "corporateweb"%>
					<%=link_to "Wordpress",list_corpo_groups_teams_path(owner_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::WORDPRESS),class: "list-group-item",id: "corporatewordpress"%>
					<%=link_to "Mobile",list_corpo_groups_teams_path(owner_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::MOBILE),class: "list-group-item",id: "corporatemobile"%>
					<%=link_to "Network",list_corpo_groups_teams_path(owner_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::NETWORK),class: "list-group-item",id: "corporatenetwork"%>
				</div>
			</div>
		<%end%>
		<%unless current_user.is_admin?%>
			<div class="list-group panel sidebar fill">
				<a href="#my_scans" class="list-group-item list-group-item-info" data-toggle="collapse" data-parent="#MainMenu">Personal Apps <i class="fa fa-caret-down pull-right"></i></a>
				<div id="my_scans">
					<%=link_to "Source Code",list_apps_repos_path(scan_type: AppConstants::ScanTypes::STATIC),class: "list-group-item",id: "static"%>
					<%=link_to "Web",list_apps_repos_path(scan_type: AppConstants::ScanTypes::WEB),class: "list-group-item",id: "web"%>
					<%=link_to "Wordpress",list_apps_repos_path(scan_type: AppConstants::ScanTypes::WORDPRESS),class: "list-group-item",id: "wordpress"%>
					<%=link_to "Mobile",list_apps_repos_path(scan_type: AppConstants::ScanTypes::MOBILE),class: "list-group-item",id: "mobile"%>
					<%=link_to "Network",list_apps_repos_path(scan_type: AppConstants::ScanTypes::NETWORK),class: "list-group-item",id: "network"%>
					<%#=link_to "Hardcode Secret Token",list_apps_repos_path(scan_type: AppConstants::ScanTypes::HARDCODE),class: "list-group-item",id: "secrettoken"%>
				</div>
			</div>
		<%end%>
	</nav>
</div>
<script>
$(document).ready(function(){
	var scan_type = '<%= params[:is_scheduled].present? ? "scheduled" : params[:scan_type]%>';
	var owner_type= '<%=params[:owner_type]%>';
	$("#" + owner_type.toLowerCase() + scan_type.toLowerCase()).addClass("active");
});
</script>

web/app/app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-header">
		<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
			<i class="icon-reorder"></i>
		</button>
		<a class="navbar-brand" href="<%=root_path%>">
			Jackhammer
		</a>
	</div>
	<nav class="collapse navbar-collapse">
		<ul class="nav navbar-nav navbar-left nav-pills1">
		</ul>
		<ul class="nav navbar-nav navbar-right nav-pills1">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#" onclick="update_notifications(this)">
					Notifications <span class="badge badge-danger notification-text"> <%=notifications_count = current_user.alert_notifications.where(read: false).count%></span> 
				</a>
				<%if notifications_count > 0%>
					<ul class="dropdown-menu dropdown-alerts">
						<%=render 'layouts/alert_notifications'%>
					</ul>
				<%end%>
				<!-- /.dropdown-alerts -->
			</li>
			<!-- /.dropdown -->
			<%if !current_user.is_admin? && Setting.application_mode != AppConstants::UserMode::SINGLE_USER%>
				<li class="dropdown <%=current_class?('/dashboards')%>">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<strong>DASHBOARD</strong>
						<span class="glyphicon glyphicon-chevron-down"></span>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Corporate Dashbaord".html_safe, display_dashboards_path(dashboard_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::STATIC)%></li>
						<li><%=link_to "Team Dashboard".html_safe,display_dashboards_path(dashboard_type: AppConstants::OwnerTypes::TEAM,scan_type: AppConstants::ScanTypes::STATIC) unless current_user.is_security_member?%></li>
						<li><%=link_to "Personal Dashboard".html_safe,display_dashboards_path(dashboard_type: AppConstants::OwnerTypes::PERSONAL,scan_type: AppConstants::ScanTypes::STATIC)%></li>
					</ul>
				</li>
			<%else%>
				<%if Setting.application_mode == AppConstants::UserMode::SINGLE_USER %>
					<li class="<%=current_class?('/dashboards')%>"><%= link_to "Dashboard".html_safe, display_dashboards_path(dashboard_type: AppConstants::OwnerTypes::PERSONAL,scan_type: AppConstants::ScanTypes::STATIC)%></li>
				<%else%>
					<li class="<%=current_class?('/dashboards')%>"><%= link_to "Dashboard".html_safe, display_dashboards_path(dashboard_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::STATIC)%></li>
				<%end%>
			<%end%>
			<%if Setting.application_mode == AppConstants::UserMode::SINGLE_USER%>
				<li class="<%=current_class?(@applications_path)%>"><%=link_to 'Applications',list_apps_repos_path(scan_type: AppConstants::ScanTypes::STATIC),method: :get%></li>
			<%else%>
				 <li class="<%=current_class?(@applications_path)%>"><%=link_to 'Applications',list_corpo_groups_teams_path(owner_type: AppConstants::OwnerTypes::CORPORATE,scan_type: AppConstants::ScanTypes::STATIC),method: :get%></li>
			<%end%>
			<%if !current_user.is_admin? && Setting.application_mode != AppConstants::UserMode::SINGLE_USER%>
				<li class="dropdown <%=current_class?('/analytics')%>">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<strong>Analytics</strong>
						<span class="glyphicon glyphicon-chevron-down"></span> 
					</a>
					<ul class="dropdown-menu">
						<li><%=link_to "Corporate Analytics".html_safe,analytics_path(analytics_type: AppConstants::OwnerTypes::CORPORATE)%></li>
						<li><%= link_to "Personal Analytics".html_safe, analytics_path(analytics_type: AppConstants::OwnerTypes::PERSONAL)%></li>
					</ul>
				</li>
			<%else%>
				<%if Setting.application_mode == AppConstants::UserMode::SINGLE_USER %>
					<li class="<%=current_class?('/analytics')%>"><%=link_to 'Analytics',analytics_path(analytics_type: AppConstants::OwnerTypes::PERSONAL)%></li>
				<%else%>
					<li class="<%=current_class?('/analytics')%>"><%=link_to 'Analytics',analytics_path(analytics_type: AppConstants::OwnerTypes::CORPORATE)%></li>
				<%end%>
			<%end%>
			<li class="<%=current_class?('/upload_scans/new')%>"><%=link_to 'ADD TARGET',add_target_scaners_path,method: :get%></li>
			<%if current_user.is_admin? || current_user.is_team_lead? || current_user.is_security_member?%>
				<li> <%=link_to 'Upload Scan',new_upload_scan_path,method: :get%></li>
			 <%end%>
			<li class="<%=current_class?(@active_nav_class)%>"> <%=link_to "Scans",scaners_path(owner_type: get_owner_type,scan_type: AppConstants::ScanTypes::STATIC)%></li>
			<%if !current_user.is_admin? && Setting.application_mode != AppConstants::UserMode::SINGLE_USER %>
				<li class="<%=current_class?('/filters/apply_filter')%> dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<strong>Filters</strong>
						<span class="glyphicon glyphicon-chevron-down"></span>
					</a>
					<ul class="dropdown-menu">
						<li><%=link_to "Corporate Filters",apply_filter_filters_path(filter_type: AppConstants::OwnerTypes::CORPORATE)%></li>
						<li><%=link_to "Personal Filters".html_safe,apply_filter_filters_path(filter_type: AppConstants::OwnerTypes::PERSONAL)%></li>
					</ul>
				</li>
			<%else%>
				<%if Setting.application_mode == AppConstants::UserMode::SINGLE_USER %>
					<li class="<%=current_class?('/filters/apply_filter')%>  dropdown"><%=link_to "Filters",apply_filter_filters_path(filter_type: AppConstants::OwnerTypes::PERSONAL)%></li>
				<%else%>
					<li class="<%=current_class?('/filters/apply_filter')%>  dropdown"><%=link_to "Filters",apply_filter_filters_path(filter_type: AppConstants::OwnerTypes::CORPORATE)%></li>
				<%end%>
			<%end%>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<span class="glyphicon glyphicon-user"></span>
					<strong><%=current_user.name.present? ? current_user.name : current_user.email%></strong>
					<span class="glyphicon glyphicon-chevron-down"></span>
				</a>
				<ul class="dropdown-menu">
					<li><%=link_to "<span class='glyphicon glyphicon-user icon-size pull-right'></span> Profile".html_safe,edit_user_registration_path %></li>
					<li><%=link_to "<span class='fa fa-book pull-right'></span>User Guide".html_safe,"https://jch.olacabs.com/userguide",target: '_blank'%></li>
					<%if current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER%>
						<li><%=link_to "#{bootstrap_icon('glyphicon-cog')} Settings".html_safe,scan_types_path%></li>
					<%else%>
						<li><%=link_to "#{bootstrap_icon('glyphicon-cog')} Settings".html_safe,severity_settings_path%></li>
					<%end%>
					<%if can_manage_roles?%>
						<li><%=link_to "#{font_awesome_icon('fa-users ')} Roles/Users".html_safe,users_path %></li>
					<%end%>
					<li class="divider navbar-login-session-bg"></li>
					<li><%= link_to "#{bootstrap_icon('glyphicon-log-out')} Sign Out".html_safe, destroy_user_session_path, method: :delete%></li>
				</ul>
			</li>
		</ul>
	</nav>
</div>

web/app/app/views/layouts/_repo_results.html.erb
<div id="sidebar-wrapper">
	<nav class="navbar navbar-default sidebar fill" role="navigation">
		<ul class="nav navbar-nav ">
			<li>
				<h2 class="animated" style="margin-left:10px;">Repo Results</h2>
			</li>
			<li class="<%=current_class?('/repos/repo_summary')%>"><%=link_to "Vulnerability Trending #{sidebar_icons('fa-line-chart')}".html_safe,repo_summary_repos_path(repo_id: params[:repo_id],scan_type: params[:scan_type],owner_type: params[:owner_type])%></li>
			<%if current_user.is_admin? || current_user.is_security_member? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER%>
				<li class="<%=current_class?(@repo_tools_results_active_path)%>"><%=link_to "Tools Result #{sidebar_icons('fa fa-wrench')}".html_safe,repo_tool_wise_findings_repos_path(repo_id: params[:repo_id],scan_type: params[:scan_type],owner_type: params[:owner_type])%></li> 
			<%end%>
			<li class="dropdown open <%=@sev_active_class_not_false%>">
				<a href="#severity" data-toggle="collapse">Repo Findings <i class="fa fa-caret-down"></i><%=sidebar_icons('fa fa-tasks').html_safe%></a>
				<div id="severity">
					<ul class="nav" role="menu">
						<%=link_to repo_results_icons('fa-exclamation-triangle','Critical'),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Critical',scan_type: params[:scan_type],owner_type: params[:owner_type]),class: "list-group-item"%>
						<%=link_to repo_results_icons('fa-level-up','High'),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'High',scan_type: params[:scan_type],owner_type: params[:owner_type]),class: "list-group-item"%>
						<%=link_to repo_results_icons('fa-arrows-h','Medium'),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Medium',scan_type: params[:scan_type],owner_type: params[:owner_type]),class: "list-group-item"%>
						<%=link_to repo_results_icons('fa-level-down','Low'),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Low',scan_type: params[:scan_type],owner_type: params[:owner_type]),class: "list-group-item"%>
						<%=link_to repo_results_icons('fa-info-circle','Info'),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Info',scan_type: params[:scan_type],owner_type: params[:owner_type]),class: "list-group-item"%>
					</ul>
				</div>
			</li>
			<%#if current_user.is_admin? || current_user.is_security_member?%>
				<li class="dropdown <%=@sev_active_class_with_false%>">
					<a href="#false_severity" data-toggle="collapse">False Positive Findings <i class="fa fa-caret-down"></i><%=sidebar_icons('fa fa-tasks').html_safe%></a>
					<div id="false_severity" class='collapse'>
						<ul class="nav" role="menu">
							<%=link_to repo_results_icons('fa-exclamation-triangle','Critical',false),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Critical',scan_type: params[:scan_type],owner_type: params[:owner_type],false_finds: true),class: "list-group-item"%>
							<%=link_to repo_results_icons('fa-level-up','High',false),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'High',scan_type: params[:scan_type],owner_type: params[:owner_type],false_finds: true),class: "list-group-item"%>
							<%=link_to repo_results_icons('fa-arrows-h','Medium',false),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Medium',scan_type: params[:scan_type],owner_type: params[:owner_type],false_finds: true),class: "list-group-item"%>
							<%=link_to repo_results_icons('fa-level-down','Low',false),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Low',scan_type: params[:scan_type],owner_type: params[:owner_type],false_finds: true),class: "list-group-item"%>
							<%=link_to repo_results_icons('fa-info-circle','Info',false),repo_severity_wise_findings_repos_path(repo_id: params[:repo_id],severity: 'Info',scan_type: params[:scan_type],owner_type: params[:owner_type],false_finds: true),class: "list-group-item"%>
						</ul>
					</div>
				</li>
			<%#end%>
		</ul>
	</nav>
</div>

web/app/app/views/layouts/_scan_results.html.erb
<div id="sidebar-wrapper">
	<nav class="navbar navbar-default sidebar fill" role="navigation">
		<ul class="nav navbar-nav ">
			<li>
				<h2 class="animated" style="margin-left:10px;">Scan Results</h2>
			</li>
			<li class="<%=current_class?('/scaners/list_scan_results')%>"><%=link_to "Vulnerability Trending <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-line-chart'></span>".html_safe,list_scan_results_scaners_path(scan_id: params[:scan_id])%></li>
			<li class="<%=current_class?(@scan_wise_results_active_path)%>"><%=link_to "Tools Result <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-wrench'></span>".html_safe,scan_wise_results_scaners_path(scan_id: params[:scan_id])%></li> 
			<li class="dropdown open <%=current_class?('/scaners/severity_results')%>">
				<a href="#severity" data-toggle="collapse">Results <i class="fa fa-caret-down"></i><span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-tasks"></span></a>                   
				<div id="severity">
					<ul class="nav" role="menu">
						<%=link_to "<i class='fa fa-exclamation-triangle critical' aria-hidden='true'></i> Critical <span class='critical-row badge'> #{@scan.critical_count}</span> ".html_safe,severity_results_scaners_path(scan_id: params[:scan_id],severity: 'Critical'),class: "list-group-item"%>
						<%=link_to "<i class='fa fa-level-up high' aria-hidden='true'></i> High <span class='high-row badge'>#{@scan.high_count} </span>".html_safe,severity_results_scaners_path(scan_id: params[:scan_id],severity: 'High'),class: "list-group-item"%>
						<%=link_to "<i class='fa fa-arrows-h medium' aria-hidden='true'></i> Medium <span class='medium-row badge'>#{@scan.medium_count}</span>".html_safe,severity_results_scaners_path(scan_id: params[:scan_id],severity: 'Medium'),class: "list-group-item"%>
						<%=link_to "<i class='fa fa-level-down low' aria-hidden='true'></i> Low <span class='low-row badge'> #{@scan.low_count} </span>".html_safe,severity_results_scaners_path(scan_id: params[:scan_id],severity: 'Low'),class: "list-group-item"%>
						<%=link_to "<i class='glyphicon glyphicon-info-sign info' aria-hidden='true'></i> Info <span class='info-row badge'>#{@scan.info_count} </span>".html_safe,severity_results_scaners_path(scan_id: params[:scan_id],severity: 'Info'),class: "list-group-item"%>
					</ul>
				</div>
			</li>
		</ul>
	</nav>
</div>

web/app/app/views/layouts/_user_roles.html.erb
<div id="sidebar-wrapper">
	<nav class="navbar navbar-default sidebar fill">
		<ul class="nav navbar-nav ">
			<li class="<%=current_class?(@user_active_path)%>"><%=link_to "Users <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-user'></span>".html_safe,users_path%></li>
			<li class="<%=current_class?(@team_active_path)%>"><%=link_to "Teams <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-users'></span>".html_safe,list_groups_teams_path%></li>
			<li class="<%=current_class?(@roles_active_path)%>"><%=link_to "Roles <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-tasks'></span>".html_safe,roles_path%></li>
			<!--<li class="<%#=current_class?('/functionalities')%>"><%#=link_to "Modules <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-puzzle-piece'></span>".html_safe,functionalities_path if current_user.is_admin?%></li>-->
			<!--<li class="animated fadeInRight"><b><%#=link_to "<i class='fa fa-lock' aria-hidden='true'></i>CRUD Operations".html_safe,permissions_path if current_user.is_admin?%></b></li>-->
		</ul>
	</nav>
</div>

web/app/app/views/layouts/_user_settings.html.erb
<div id="sidebar-wrapper">
	<nav class="navbar navbar-default sidebar fill" role="navigation">
		<ul class="nav navbar-nav ">
			<li>                       
				<h2 class="animated" style="margin-left:10px;">Settings</h2>
			</li>
			<%if current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER%>
				<li class="<%=current_class?(@scan_type_class)%>"><%=link_to "Scanner Types <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-tripadvisor'></span>".html_safe,scan_types_path%></li>
				<li class="dropdown <%=current_class?(@list_scans_class)%> open">
					<a href="#tools" class="dropdown-toggle" data-toggle="collapse"> Scan Tools <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-wrench"></span></a>
					<div id="tools">
						<ul class=" nav" role="menu">
							<%=link_to "List Tools <span style='font-size:16px;'></span>".html_safe,scanner_settings_path,class: "list-group-item"%>
							<%=link_to "Upgrade Tools ".html_safe,tools_list_tasks_path,class: "list-group-item"%>
							<%=link_to "Tools Configuration".html_safe,configure_view_tasks_path,class: "list-group-item"%>
							<%#=link_to "Hard Coded Secret ".html_safe,truffle_params_tasks_path,class: "list-group-item"%>
						</ul>
					</div>

				</li>
				<li class="<%=current_class?('/settings/jira')%>"><%=link_to "Jira #{image_tag('iconJIRA16.jpg',class: 'pull-right hidden-xs showopacity',style: 'font-size:16px')}".html_safe,jira_settings_path%></li>
				<%unless Setting['github'].present? && Setting['github']['username'].present?%>
					<li class="<%=current_class?('/settings/gitlab')%>"><%=link_to "Gitlab  <span style='font-size:16px;'  class='pull-right hidden-xs showopacity fa fa-gitlab' aria-hidden='true'></span>".html_safe,gitlab_settings_path%></li>
				<%end%>
				<%unless Setting['gitlab'].present? && Setting['gitlab']['username'].present?%>
					<li class="<%=current_class?('/settings/github')%>"><%=link_to "Github <i class='fa fa-github pull-right hidden-xs showopacity' aria-hidden='true'></i>".html_safe,github_settings_path%></li>
				<%end%>
				<%if Setting.application_mode != AppConstants::UserMode::SINGLE_USER%>
					<li class="<%=current_class?('/settings/signup_role')%>"><%=link_to "Configure Sign Up Role <i class='fa fa-user pull-right hidden-xs showopacity' aria-hidden='true'></i>".html_safe,signup_role_settings_path%></li>
				<%end%>
				<!--<li><%#=link_to "Alert Notifications <i class='fa fa-bell pull-right hidden-xs showopacity' aria-hidden='true' aria-hidden='true'></i>".html_safe,get_mail_info_settings_path%></li>-->
				<!--<li class="<%#=current_class?('/settings/get_check_mark_details')%>"><%#=link_to "Checkmarx <i class='glyphicon glyphicon-check pull-right hidden-xs showopacity'></i>".html_safe,get_check_mark_details_settings_path%></li>-->
			<%end%>
			<li class="<%=current_class?('/settings/severity')%>"><%=link_to "Severity <span style='font-size:16px;' class='pull-right hidden-xs showopacity fa fa-exclamation-triangle'></span>".html_safe,severity_settings_path%></li>
			<li class="dropdown open <%=current_class?(@nav_notification_class)%>">
				<a href="#notifications" class="dropdown-toggle" data-toggle="collapse">Alert Notifications <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity fa fa-bell"></span></a>
				<div id="notifications">
					<ul class="nav" role="menu">
						<%=link_to "Configure Mails".html_safe,get_mail_info_settings_path,class: "list-group-item"%>
						<%=link_to "SMTP Settings".html_safe,get_sender_mail_settings_path,class: "list-group-item" if current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER%>
					</ul>
				</div>
			</li> 
		</ul>
	</nav>
</div>