web/app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'
Rails.application.routes.draw do
	mount Sidekiq::Web => '/sidekiq'
	resources :tasks do
		collection do
			get 'tools_list'
			post 'update_tool'
			get 'configure_view'
			post 'update_configurations'
		end
	end
	resources :tags
	resources :permissions
	resources :functionalities
	devise_scope :user do
		root :to => 'users/sessions#new'
	end

	devise_for :users,controllers: {registrations: "users/registrations",omniauth_callbacks: "users/omniauth_callbacks"}
	resources :users do
		collection do
			get :autocomplete_user_name
			post :add
		end
	end
	resources :scaners do
		collection do
			get 'run'
			get 'load_projects'
			get 'load_branches'
			post 'store_bulk_scans'
			get 'list_scan_results'
			get 'severity_results'
			get 'scan_wise_results'
			get 'my_scans'
			get 'start_scan_for_all_repo'
			get 'add_dynamic_scans'
			get 'scans_diff'
			get 'run_truffle'
			get 'download_results'
			post 'change_find_status'
			get 'add_target'
			post 'unschedule'
		end
	end
	resources :findings do
		resources :comments
		resources :uploads do
			collection do 
				get 'download_file'
			end
		end
		resources :tags
		collection do
			get 'details'
			post 'change_status'
			post 'add_new_tag'
			post 'add_tag'
			delete 'delete_file'
			post 'change_false_positive'
			post 'publish_to_jira'
			post 'change_to_not_exploitable'
			get 'next_finding'
			post 'save_tag'
		end
	end
	resources :teams do
		collection do
			get 'fetch_projects'
			get 'list_groups'
			get 'repo_summary'
			get 'export_findings'
			get 'list_corpo_groups'
		end
	end
	resources :repos do
		collection do
			 get 'repo_summary'
			 get 'repo_tool_wise_findings'
			 get 'repo_severity_wise_findings'
			 get 'repo_channel_results'
			 get 'get_team_repos'
			 get 'list_apps'
			 get 'false_positive_finds'
			 delete 'delete_repo_channel_results'
		end
	end
	resources :dashboards do
		collection do
			get 'display'
			get 'static'
			get 'web'
			get 'wordpress'
			get 'mobile'
			get 'network'
		end
	end

	resource :settings do
		collection do
			get 'severity'
			get 'scanner'
			get 'jira'
			get 'gitlab'
			get 'github'
			get 'signup_role'
			get 'get_mail_info'
			get 'get_sender_mail'
			get 'pull_corporate_info'
			post 'update_details'
			post 'update_mail_info'
			post 'update_severities'
		end
	end	
	resources :user_management,:controller => :user_management
	resources :roles
	resources :groups
	resources :functionalities
	resources :analytics do
		collection do
			get :load_charts
			post :save_filters
			get :get_desc_wise
		end
	end
	resources :filters do
		collection do
			get :apply_filter
			post :results
		end
	end
	resources :scan_types
	resources :upload_scans do
		collection do
			post 'save_team'
		end
	end
	resources :alert_notifications do
		collection do
			post 'update_alerts'
		end
	end
	get 'restricted', :to=> 'errors#unauthorized'
	%w( 404 422 500 ).each do |code|
		get code, :to => "errors#show", :code => code
	end

end

web/app/app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base 
end

web/app/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	def severity
		@tasks = current_user.tasks.map(&:name)
	end
	def scanner
		unauthorized_page unless current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER
		@list_scans_class = "/settings/scanner"
		@tasks = current_user.tasks.map(&:name)
		@scan_types = ScanType.all
		@static_tools = Task.where(scan_type: 'Static Tools').order(:group).group(:group)

	end
	def update_details
		is_unauthorized = true
		is_unauthorized = false if current_user.is_admin? 
		is_unauthorized = false if Setting.application_mode == AppConstants::UserMode::SINGLE_USER
		if is_unauthorized
			unauthorized_page  
		else
			if params[:settings][:jira].present?
				jira_options = {
					:site => params[:settings][:jira]['host'],
					:username => params[:settings][:jira]['username'],
					:password => params[:settings][:jira]['password'],
					:context_path => '' ,#Setting.jira['context_path'],
					:auth_type => :basic
				}
				jira = JIRA::Client.new(jira_options)
				begin
					jira_project = jira.Project.all.select { |p| p.name.downcase == params[:settings][:jira]["default_project"].downcase }	
					if jira_project.present?
						update_settings
						flash[:notice] = "Jira details are updated"
					else
						flash[:notice] = "Given project is not in jira,Please give right project "
					end
				rescue Exception=>e
					flash[:error] = "Jira is #{e.message}"
				end
				respond_to do |format|
					format.js
				end
			else
				update_settings
				flash[:notice] = "Settings are updated successfully"
				respond_to do |format|
					format.js
				end
			end
		end
	end
	def jira
		unauthorized_page unless current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER
	end
	def gitlab
		unauthorized_page unless current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER 
	end
	def github
		unauthorized_page unless current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER
	end
	def signup_role
		unauthorized_page unless current_user.is_admin? && Setting.application_mode != AppConstants::UserMode::SINGLE_USER
		@roles = Role.all
	end
	def update
		#unauthorized_page unless current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER
		if Setting.pipeline['enabled_tools'].present?
			@enabled_tools = Setting.pipeline['enabled_tools'].split(",")
		else
			@enabled_tools = []
		end
		params[:task].each do |key,value|
			task = Task.find_by_name(key)
			if value.to_i == 1
				@enabled_tools << key 
			else
				@enabled_tools.delete(key)
			end
		end
		Setting.merge!(:pipeline, {"enabled_tools"=>@enabled_tools.uniq.join(",")}) if current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER
		respond_to do |format|
			flash[:notice] = "Tools settings Saved successfully."
			format.js
		end 
	end
	def update_severities
		params[:task].each do |key,value|
			task = Task.find_by_name(key)
			if value.to_i == 1 && !current_user.tasks.include?(task)
				current_user.tasks <<  task
			elsif value.to_i == 0 && current_user.tasks.include?(task)
				current_user.tasks.destroy(task)
			end
		end
		respond_to do |format|
			flash[:notice] = "Severity settings are updated"
			format.js
		end
	end
	def get_mail_info
		@nav_notification_class = '/settings/get_mail_info'
		@notification = current_user.notification
	end
	def update_mail_info
		if current_user.notification.present?
			current_user.notification.update(notification_params)
		else
			notification = Notification.create(notification_params)
			notification.user = current_user
			notification.save
		end
		respond_to do |format|
			flash[:notice] = "e-mails are successfully updated"
			format.html { redirect_to :action=>"get_mail_info"}
		end
	end
	def get_sender_mail
		unauthorized_page unless current_user.is_admin? || Setting.application_mode == AppConstants::UserMode::SINGLE_USER
		@nav_notification_class = '/settings/get_sender_mail'
	end
	def pull_corporate_info
		unauthorized_page unless current_user.is_admin?
		respond_to do |format|
			if Setting[params[:pull_repos][:git_type]].present?
				if params[:pull_repos][:git_type] == 'gitlab'
					klass = GitlabPullInfoWorker
				elsif params[:pull_repos][:git_type] == 'github'
					klass = GithubPullInfoWorker
				end
				klass.perform_async
				flash[:notice] = "Pulling git repos info started."
			else
				flash[:alert] = "Api endpoint && Api access token are not configured, Please configure it"
			end
			format.js
		end
	end
	private
	def notification_params
		params.require(:notifications).permit(:critical_count,:high_count,:medium_count,:low_count,:info_count,:critical_email,:high_email,:medium_email,:low_email,:info_email)
	end
end

web/app/app/helpers/settings_helper.rb
module SettingsHelper
	def is_tool_enabled?(task_name)
		return true if Setting.pipeline.present? && Setting.pipeline["enabled_tools"].include?(task_name)
		return false
	end
end

web/app/app/views/settings/add_new_tool.html.erb
<div class="ts-main-content">   
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="container">
			<div id="settings_message"></div>
			<div class='row'>
				<div class='col-md-10'>
					<div class="panel panel-default">
						<div class="panel-heading"><h4>Add New Tool</h4></div>
						<div class="panel-body">
							<%= form_for(:new_task,method: 'POST',url: save_new_tool_settings_path ) do |f| %>
								<div class='row'>
									<div class='form-group col-md-4'>
										<%=f.label :tool_name%>
										<%=f.text_field :name,class: 'form-control'%>
									</div>
								</div>
								<div class='row'>
									<div class='form-group col-md-4'>
										<%=f.label :supported_language%>
										<%=f.select :group ,[["Ruby","Ruby"],["Java","Java"],["Javascript","Javascript"]],{prompt: 'Select Language'},{class: "form-control"}%>
									</div>
								</div>	
								<div class='row'>
									<div class='form-group col-md-4'>
										<%=f.label :category%>
										<%= f.select :scan_type, ScanType.all.map { |type| [type.name,type.id] },{},{class: "form-control",onchange: "enable_file_field();"}%>
									</div>
								</div>
								<div class='row'>
									<div class='form-group col-md-4'>

										<%= f.submit class: 'btn btn-primary'%>
									</div>
								</div>
							<% end %>

							<%= link_to 'Back', scan_types_path %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

web/app/app/views/settings/edit_tools.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="container">
			<div id="settings_message"></div>
		</div>
		<div class='container'>
			<div class='row'>
				<div class='col-md-12'>
					<div class="panel panel-default">
						<div class="panel-heading">Tools</div>
						<div class="panel-body">		
							<table class='table'>
								<thead>
									<th>Name</th>
									<th>Scan Type</th>
									<th>Language</th>
									<th>Edit</th>
									<th>Delete</th>
								</thead>
								<tbody>
									<%@tools.each do |each_tool| %>
										<tr>
											<td><%=each_tool.name%></td>			
											<td><%=each_tool.scan_type.name%></td>
											<td><%=each_tool.group%>
											<td>
												<%=link_to('<i class="fa fa-pencil-square-o"> </i>'.html_safe,update_tool_settings_path(each_tool),title: 'Delete',method: :delete, remote: true,confirm: "Confirm deletion?")%>
											</td>
											<td>
												<%=link_to('<i class="glyphicon glyphicon-remove-circle text-danger"> </i>'.html_safe,destroy_tool_settings_path(id: each_tool.id),title: 'Delete',method: :delete,confirm: "Confrm deletion?")%>
											</td>
										</tr>
									<%end%>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

web/app/app/views/settings/get_sender_mail.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="continer">
			<div id="settings_message"></div>
		</div>
		<div class='container'>
			<ul class="breadcrumb">
				<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
				<li class="breadcrumb-item">SMTP Settings</li>
			</ul>
			<div class='row'>
				<div class='col-md-8'> 
					<div class="panel panel-default">
						<div class="panel-heading"><h4>SMTP Settings</h4></div>
						<div class="panel-body">
							<%= form_for(:settings, url: update_details_settings_path ,method: :POST ,remote: true,:html=>{role: "form"}) do |form| %>
								<%= form.fields_for :notification do |f| %>
									<div class="form-group">
										<%=f.label :host,"Application URL #{field_info("Ex: localhost:3000")}".html_safe%>
										<%= f.text_field :host, autofocus: true,requred: true,class: "form-control",value: Setting["notification"].present? ? Setting["notification"]["host"] : ""%>
									</div>
									<div class="form-group">
										<%=f.label :address,"Address #{field_info("Ex: smtp.gmail.com")}".html_safe%>
										<%= f.text_field :address, autofocus: true,requred: true,class: "form-control",value: Setting["notification"].present? ? Setting["notification"]["address"] : ""%>              
									</div>
									<div class="form-group">                                               
										<%=f.label :smtp_host,"SMTP Domain #{field_info("Ex: mail.gmail.com")}".html_safe%>
										<%= f.text_field :domain, autofocus: true,requred: true,class: "form-control",value: Setting["notification"].present? ? Setting["notification"]["domain"] : ""%>
									</div>          
									<div class="form-group " >
										<%=f.label :email,"From Email Address"%>
										<%= f.text_field :email, autofocus: true,requred: true,class: "form-control",value: Setting["notification"].present? ? Setting["notification"]["email"]: ""%>
									</div>                                          
									<div class="form-group ">
										<%=f.label :password,"SMTP Password #{field_info("Email Password")}".html_safe%>
										<%= f.password_field :password, autofocus: true,requred: true, class: "form-control"%>
									</div>                                                                  
									<div class="form-group ">
										<%=f.label :smtp_port,"SMTP Port #{field_info("Ex: 587")}".html_safe%>
										<%= f.text_field :port, autofocus: true,requred: true, class: "form-control",value: Setting["notification"].present? ? Setting["notification"]["port"] : "" %>
									</div>
									<div class="form-group ">
										<%=f.label :encryption_type,"Type of Encryption"%>
										<%= f.select :encryption_type,options_for_select([["None", "None"],["SSL", "SSL"],["TLS", "TLS"]]),{},{class: "form-control"} %>
									</div>
									<div class="form-group ">
										<%=f.label :smtp_authentication,"SMTP Authentication"%>
										<%= f.select :smtp_authentication,options_for_select([["Yes", "yes"],["No", "no"]]),{},{class: "form-control"} %>
									</div>
									<div class="form-group" >                                                           
										<%= f.submit "Save",class: 'btn btn-danger'%>                                        
									</div>               
								<%end%>
							<%end%>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

web/app/app/views/settings/github.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="continer">
			<div id="settings_message"></div>
		</div>

		<div class='container'>
			<div class='row'>
				<div class="row">
					<ul class="breadcrumb">
						<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
						<li class="breadcrumb-item">Github Details</li>
					</ul>   
				</div> 
				<div class='col-md-8'>
					<div class="panel panel-default">
						<div class="panel-heading">Github Details</div>
						<div class="panel-body">
							<div id="category" data-id="github">
								<%= form_for(:settings, url: update_details_settings_path,method: :POST ,remote: true,:html=>{role: "form"}) do |form| %>
									<%= form.fields_for :github do |f| %>
										<%=f.hidden_field :user_id,value: current_user.id%>
										<fieldset>
											<legend>General</legend>
											<div class="form-group">
												<%=f.label :host,"Host #{field_info("Ex: https://gitlab.example.com")}".html_safe%>
												<%=f.text_field :host,class: "form-control",value: Setting["github"].present? ? Setting["github"]["host"] : ""%>
											</div>
											<div class="form-group">
												<%=f.label :username%>
												<%=f.text_field :username,class: "form-control",value: Setting["github"].present? ? Setting["github"]["username"] : ""%>
											</div>
											<div class="form-group">
												<%=f.label :password%>
												<%=f.password_field :password,class: "form-control"%>
											</div>
											<div class="form-group">
												<%=f.label :api_endpoint,"API Endpoint #{field_info("Ex: https://gitlab.example.com/api/v3")}".html_safe%>
												<%=f.text_field :api_end_point,class: "form-control",value: Setting["github"].present? ? Setting["github"]["api_end_point"] : ""%>
											</div>
											<div class="form-group">
												<%=f.label :api_access_token%>
												<%=f.text_field :api_access_token,class: "form-control"%>
											</div>
										</fieldset>
										<br><br>
										<fieldset>
											<legend>OAuth</legend>
											<span data-id="oauth">
												<div class="form-group">
													<%=f.label :client_ID,"Client ID #{optional_text}".html_safe%>
													<%=f.text_field :client_id,class: "form-control",value: Setting["github"].present? ? Setting["github"]["client_id"] : ""%>
												</div>
												<div class="form-group">
													<%=f.label :client_secret,"Client Secret #{optional_text}".html_safe%>
													<%=f.text_field :client_secret,class: "form-control"%>
												</div>
											</span>
										</fieldset>
										<%=f.submit "Update GitHub Settings",class: "btn btn-primary pull-right"%>
									<%end%>
								<%end%>
							</div>
						</div>
					</div>

				</div>
				<%if  Setting.application_mode != AppConstants::UserMode::SINGLE_USER%>
					<div class='col-md-4 top-buffer'>       
						<%= form_for(:pull_repos,url: pull_corporate_info_settings_path,method: 'GET',remote: true) do |f|%>
							<%=f.submit "Fetch repo, teams, users",class: "btn btn-primary"%>
							<%=f.hidden_field :git_type,:value=>"github"%>
							<%=f.hidden_field :git_worker,:value=>"github"%>
							<a href="#" data-toggle="popover" data-trigger="hover" font-size="8px;" data-content="Clicking on Pull Corporate Info button , Jackhammer pulls the Users/Groups/Repos info .Make sure that API Endpoint && API Access token are configured">
								<i class='glyphicon glyphicon-info-sign text-info'></i>
							</a>
						<%end%>
					</div>
				<%end%>
			</div>
		</div>
	</div>
</div>

web/app/app/views/settings/gitlab.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="continer">
			<div id="settings_message"></div>
		</div>

		<div class='container'>
			<ul class="breadcrumb">
				<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
				<li class="breadcrumb-item">Gitlab Details</li>
			</ul>
			<div class='col-md-8'>
				<div class="panel panel-default">
					<div class="panel-heading">Gitlab Details</div>
					<div class="panel-body">
						<div id="category" data-id="github">
							<%= form_for(:settings, url: update_details_settings_path,method: :POST ,remote: true,:html=>{role: "form"}) do |form| %>
								<%= form.fields_for :gitlab do |f| %>
									<%=f.hidden_field :user_id,value: current_user.id%>
									<fieldset>
										<legend>General</legend>
										<div class="form-group">
											<%=f.label :host,"Host #{field_info("Ex: https://gitlab.example.com")}".html_safe%>
											<%=f.text_field :host,class: "form-control",value: Setting["gitlab"].present? ? Setting["gitlab"]["host"] : ""%>
										</div>
										<div class="form-group">
											<!--<span class='setting-label'> api_end_point</span>-->
											<%=f.label :username%>
											<%=f.text_field :username,class: "form-control",value: Setting["gitlab"].present? ? Setting["gitlab"]["username"] : ""%>
										</div>
										<div class="form-group">
											<%=f.label :password%>
											<%=f.password_field :password,class: "form-control"%>
										</div>
										<div class="form-group">
											<%=f.label :api_endpoint,"API Endpoint #{field_info("Ex: https://gitlab.example.com/api/v3")}".html_safe%>
											<%=f.text_field :api_end_point,class: "form-control",value: Setting["gitlab"].present?.present?  ? Setting["gitlab"]["api_end_point"] : ""%>
										</div>
										<div class="form-group">
											<%=f.label :api_access_token%>
											<%=f.text_field :api_access_token,class: "form-control"%>
										</div>
									</fieldset>
									<br><br>
									<fieldset>
										<legend>OAuth</legend>
										<span data-id="oauth">
											<div class="form-group">
												<%=f.label :client_ID,"Client ID #{optional_text}".html_safe%>
												<%=f.text_field :client_id,class: "form-control",value: Setting["gitlab"].present? ? Setting["gitlab"]["client_id"] : ""%>
											</div>
											<div class="form-group">
												<%=f.label :client_secret,"Client Secret #{optional_text}".html_safe%>
												<%=f.text_field :client_secret,class: "form-control"%>
											</div>
										</span>
									</fieldset>
									<%=f.submit "Update Gitlab Settings",class: "btn btn-primary pull-right"%>
								<%end%>
							<%end%>
						</div>
					</div>
				</div>

			</div>
			<%if  Setting.application_mode != AppConstants::UserMode::SINGLE_USER%>
				<div class='col-md-4 top-buffer'>
					<%= form_for(:pull_repos,url: pull_corporate_info_settings_path,method: 'GET',remote: true) do |f|%>
						<%=f.submit "Fetch repo, teams, users",class: "btn btn-primary"%>
						<%=f.hidden_field :git_type,:value=>"gitlab"%>
						<a href="#" data-toggle="popover" data-trigger="hover" font-size="8px;" data-content="Clicking on Pull Corporate Info button , Jackhammer pulls the Users/Groups/Repos info .Make sure that API Endpoint && API Access token are configured">
							<i class='glyphicon glyphicon-info-sign text-info'></i>
						</a>
					<%end%>
				</div>
			<%end%>
		</div>
	</div>
</div>

web/app/app/views/settings/jira.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="continer">
			<div id="settings_message"></div>
		</div>

		<div class='container'>
			<ul class="breadcrumb">
				<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
				<li class="breadcrumb-item">Jira Details</li>
			</ul>
			<div class='col-md-8'>
				<div class="panel panel-default">
					<div class="panel-heading"><h4>Jira Details</h4></div>
					<div class="panel-body">
						<%= form_for(:settings, url: update_details_settings_path,method: :POST ,remote: true,:html=>{role: "form"}) do |form| %>
							<%= form.fields_for :jira do |f| %>
								<div class="form-group">                                               
									<%=f.label :host%>
									<%= f.text_field :host, autofocus: true,requred: true,class: "form-control",value: Setting["jira"].present? ? Setting["jira"]["host"] : ""%>
								</div>          
								<div class="form-group " >
									<%=f.label :username%>
									<%= f.text_field :username, autofocus: true,requred: true,class: "form-control",value: Setting["jira"].present? ? Setting["jira"]["username"] : ""%>
								</div>                                          
								<div class="form-group " >
									<%=f.label :password%>
									<%= f.password_field :password, autofocus: true,requred: true, class: "form-control"%>
								</div>                                                                  
								<div class="form-group " >
									<%=f.label :default_project%>
									<%= f.text_field :default_project, autofocus: true,requred: true, class: "form-control",value:Setting["jira"].present? ? Setting["jira"]["default_project"] : ""%>
								</div>
								<div class="form-group" >                                                           
									<%= f.submit "Save",class: 'btn btn-danger',:onclick=> "start_spinner();"%>                                       
									<a href="#" data-toggle="popover" data-trigger="hover" font-size="8px;" data-content="In case findings project dose not match, issue will get publish to default project">
										<i class='glyphicon glyphicon-info-sign text-info'></i>
									</a>
								</div>               
							<%end%>
						<%end%>
					</div>
					<div class='jira-spinner'>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
function start_spinner()
{
	$(".jira-spinner").spin({
		lines: 12, // The number of lines to draw
		length: 7, // The length of each line
		width: 9, // The line thickness
		radius: 30, // The radius of the inner circle
		color: '#000', // #rgb or #rrggbb
		speed: 1, // Rounds per second
		trail: 60, // Afterglow percentage
		shadow: true // Whether to render a shadow
	});
}
</script>

web/app/app/views/settings/scanner.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="container">   
			<div class="row">
				<ul class="breadcrumb">
					<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
					<li class="breadcrumb-item">Enable/Disable Tools</li>
				</ul>
			</div>
			<div class='row pull-right'>
				<div class='col-md-12'>
					<%=link_to "<i class='glyphicon glyphicon-minus-sign'></i> Modify".html_safe,tasks_path,method: "GET",class: 'btn btn-danger'%>
					<%=link_to "<i class='glyphicon glyphicon-plus-sign'></i>  Add".html_safe,new_task_path,method: "GET",class: 'btn btn-success'%>
				</div>
			</div>	
			<ul class="nav nav-tabs">
				<%first_iteration = true%>
				<%@scan_types.each do |scan_type|%>
					<%if first_iteration%>
						<li class="active">
						<%else%>
							<li>
							<%end%>
							<a data-toggle="tab" href="#<%=scan_type.name.split(' ').join("_")%>"><%=scan_type.name%></a>
							</li>
							<%first_iteration = false%>
						<%end%>
			</ul>
			<div class="tab-content top-buffer">
				<%first_iteration = true%>
				<%@scan_types.each do |scan_type|%>
					<%active_class = first_iteration ? "tab-pane fade in active" : "tab-pane fade"%>
					<div id="<%=scan_type.name.split(" ").join('_')%>" class="<%=active_class%>">
						<%=form_for :task,method: "PUT",url: settings_path,remote: true do |f|%>
							<%scan_tasks = scan_type.tasks.group(:group)%>
							<%if scan_tasks.present?%>
								<div class='row'>
									<%if scan_tasks.first.group.present?%>
										<%scan_tasks.each do |each_group|%>
											<div class='col-md-6'>
												<div class="panel panel-info">
													<div class="panel-heading"><h4><%=each_group.group%></h4></div>
													<div class="panel-body">
														<%group_tools = Task.where(group: each_group.group)%>
														<%group_tools.each do |each_tool|%>
															<div class='col-md-6'>
																<div class="checkbox checkbox-slider--b-flat">
																	<label>
																		<%=f.check_box each_tool.name.to_sym,checked: is_tool_enabled?(each_tool.name) %><span ><%=each_tool.name%></span>
																	</label>
																</div>
															</div>
														<%end%>
													</div>
												</div>
											</div>
										<%end%>
									<%else%>
										<%scan_tasks = scan_type.tasks%>
										<div class='col-md-8'>
											<div class="panel panel-info">
												<div class="panel-heading"><h4><%=scan_type.name%></h4></div>
												<div class="panel-body">
													<%scan_tasks.each do |each_task|%>
														<div class='col-md-6'>
															<div class="checkbox checkbox-slider--b-flat">
																<label>
																	<%=f.check_box each_task.name.to_sym,checked: is_tool_enabled?(each_task.name)%><span ><%=each_task.name%></span>
																</label>
															</div>
														</div>
													<%end%>
												</div>
											</div>
										</div>
									<%end%>
								</div>
							<%end%>
							<%=f.submit "Save",class: 'btn btn-danger' %>
						<%end%>
					</div>
					<%first_iteration = false%>
				<%end%> 
			</div>
		</div>
	</div>
</div>

web/app/app/views/settings/update.js.erb
<%=custom_bootstrap_flash%>

web/app/app/views/settings/update_details.js.erb
<%=custom_bootstrap_flash%>
$(".jira-spinner").spin(false);

web/app/app/views/settings/update_severities.js.erb
<%=custom_bootstrap_flash%>