web/app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'
Rails.application.routes.draw do
	mount Sidekiq::Web => '/sidekiq'
	resources :tasks do
		collection do
			get 'tools_list'
			post 'update_tool'
			get 'configure_view'
			post 'update_configurations'
		end
	end
	resources :tags
	resources :permissions
	resources :functionalities
	devise_scope :user do
		root :to => 'users/sessions#new'
	end

	devise_for :users,controllers: {registrations: "users/registrations",omniauth_callbacks: "users/omniauth_callbacks"}
	resources :users do
		collection do
			get :autocomplete_user_name
			post :add
		end
	end
	resources :scaners do
		collection do
			get 'run'
			get 'load_projects'
			get 'load_branches'
			post 'store_bulk_scans'
			get 'list_scan_results'
			get 'severity_results'
			get 'scan_wise_results'
			get 'my_scans'
			get 'start_scan_for_all_repo'
			get 'add_dynamic_scans'
			get 'scans_diff'
			get 'run_truffle'
			get 'download_results'
			post 'change_find_status'
			get 'add_target'
			post 'unschedule'
		end
	end
	resources :findings do
		resources :comments
		resources :uploads do
			collection do 
				get 'download_file'
			end
		end
		resources :tags
		collection do
			get 'details'
			post 'change_status'
			post 'add_new_tag'
			post 'add_tag'
			delete 'delete_file'
			post 'change_false_positive'
			post 'publish_to_jira'
			post 'change_to_not_exploitable'
			get 'next_finding'
			post 'save_tag'
		end
	end
	resources :teams do
		collection do
			get 'fetch_projects'
			get 'list_groups'
			get 'repo_summary'
			get 'export_findings'
			get 'list_corpo_groups'
		end
	end
	resources :repos do
		collection do
			 get 'repo_summary'
			 get 'repo_tool_wise_findings'
			 get 'repo_severity_wise_findings'
			 get 'repo_channel_results'
			 get 'get_team_repos'
			 get 'list_apps'
			 get 'false_positive_finds'
			 delete 'delete_repo_channel_results'
		end
	end
	resources :dashboards do
		collection do
			get 'display'
			get 'static'
			get 'web'
			get 'wordpress'
			get 'mobile'
			get 'network'
		end
	end

	resource :settings do
		collection do
			get 'severity'
			get 'scanner'
			get 'jira'
			get 'gitlab'
			get 'github'
			get 'signup_role'
			get 'get_mail_info'
			get 'get_sender_mail'
			get 'pull_corporate_info'
			post 'update_details'
			post 'update_mail_info'
			post 'update_severities'
		end
	end	
	resources :user_management,:controller => :user_management
	resources :roles
	resources :groups
	resources :functionalities
	resources :analytics do
		collection do
			get :load_charts
			post :save_filters
			get :get_desc_wise
		end
	end
	resources :filters do
		collection do
			get :apply_filter
			post :results
		end
	end
	resources :scan_types
	resources :upload_scans do
		collection do
			post 'save_team'
		end
	end
	resources :alert_notifications do
		collection do
			post 'update_alerts'
		end
	end
	get 'restricted', :to=> 'errors#unauthorized'
	%w( 404 422 500 ).each do |code|
		get code, :to => "errors#show", :code => code
	end

end

web/app/app/controllers/upload_scans_controller.rb
class UploadScansController < ApplicationController
	def new
		unauthorized_page unless current_user.is_admin? || current_user.is_team_lead? || current_user.is_security_member?
		get_user_repos
	end
	def create
		@scaner = current_user.scaners.build(corporate_scanner_params)
		@scaner.invloved_tools = corporate_scanner_params[:source]
		save_scanner
	end
	def save_team
		@scaner = current_user.scaners.build(team_scanner_params)
		@scaner.invloved_tools = team_scanner_params[:source]
		repo_team = Repo.find(team_scanner_params[:repo_id]).team
		@scaner.team = repo_team
		save_scanner
	end
	def save_scanner
		@scaner.status = "Started uploading results...."
		respond_to do |format|
			if @scaner.save
				@scaner.update(is_upload_scan: true,owner_type: 'corporate')
				scaner_instance = ScanerInstance.create(scaner_id: @scaner.id)
				klass = "#{@scaner.source}UploadWorker".constantize
				klass.perform_async(@scaner.id)
				owner_type = current_user.is_team_lead? ? AppConstants::OwnerTypes::TEAM : AppConstants::OwnerTypes::CORPORATE
				flash[:notice] = "Scan Target added successfully"
				format.html { redirect_to :controller=>"scaners",:action=>"index",scan_type: AppConstants::ScanTypes::UPLOADED,owner_type: owner_type}
			else
				get_user_repos
				flash[:error] = "Only xml files are accepted"
				format.html { render 'new' }
			end
		end
	end
	def get_user_repos
		@user_repos = current_user.repos
		@user_repos = current_user.teams.first.repos if current_user.is_team_lead?
	end
	private
	def corporate_scanner_params
		params.require(:scaners).permit(:project_title,:target,:branch_name,:source,:project_target,:team_id,:repo_id,:branch_id,:periodic_schedule,:invloved_tools,:vulnerable_types,:owner_type,:scan_type)
	end
	def team_scanner_params
		params.require(:scaner).permit(:project_title,:target,:branch_name,:source,:project_target,:team_id,:repo_id,:branch_id,:periodic_schedule,:invloved_tools,:vulnerable_types,:owner_type,:scan_type)
	end
end

web/app/app/helpers/upload_scans_helper.rb
module UploadScansHelper
end

web/app/app/views/upload_scans/_form.html.erb
<div class="container">
	<ul class="breadcrumb">
		<li class="breadcrumb-item active">Upload Scan </li>
	</ul>
	<div class="page-header">
		<h2> Upload Scan </h2>
	</div>
	<div class="jumbotron jumbo-background">
		<div class="panel-heading">
			<ul class="nav nav-tabs">
				<!--<li class="active"><a data-toggle="tab" href="#my_project">My Scan</a></li>-->
				<%if current_user.is_team_lead?%>
					<li class="active"><a data-toggle="tab" href="#team_project">Team Scan</a></li>
				<%end%>
				<%if current_user.is_admin? || current_user.is_security_member?%>
					<li class="active"><a data-toggle="tab" href="#corporate_project">Corporate Scan</a></li>
				<%end%>
			</ul>
		</div>
		<div class="tab-content top-buffer">
			<%unless current_user.is_admin? || current_user.is_security_member?%>
				<div id="team_project" class="tab-pane fade in active">
					<%=form_for(Scaner.new,:url=>save_team_upload_scans_path,:method=>"post",:html=>{class: 'form-horizontal',role: "form"}) do |f| %>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.label :project,class: 'label-class' %>
								<%= f.select :repo_id, @user_repos.map { |repo| [repo.name,repo.id]},{prompt: 'select project'},{:class=> "selectpicker dropup show-tick show-menu-arrow",'data-live-search'=>"true",'data-show-subtext'=> "true",'data-width'=>"100%",'data-size'=>"5",:onChange=>'load_branches();'}%>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.label :scan_type,class: 'label-class' %>
								<%= f.select :scan_type, options_for_select(AppConstants::AppTypes::APP_TYPES_WITH_VALUES),{},{class: "form-control"}%>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.label :tool,class: 'label-class' %>
								<%= f.select :source, options_for_select(AppConstants::TOOLS::EXTERNAL_TOOLS),{prompt: 'select tool'},{class: "form-control selectpicker dropup show-tick show-menu-arrow"}%>
							</div>
						</div>
						<div class="form-group" id="directory_field">
							<div class='col-md-6'>
								<!-- The fileinput-button span is used to style the file input field as button -->
								<%= f.label :upload_scan,class: 'label-class' %>
								<%= f.file_field :project_target,autofocus: true,required: 'required',class: "btn btn-success file-field" %>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.submit "Upload Scan Results", :class=>"btn btn-danger"%>
							</div>
						</div>
					<%end%>
				</div>
			<%end%>
			<%if current_user.is_admin? || current_user.is_security_member?%>
				<div id="corporate_project" class="tab-pane fade in active">
					<%=form_for(:scaners,:url=>upload_scans_path,:method=>"post",:html=>{class: 'form-horizontal',id: 'upload_scan_form',role: "form"}) do |f| %>
						<div class="form-group">
							<div class='col-md-4'>
								<%= f.label :team,class: 'label-class' %>
								<%= f.select :team_id, Team.all.order(:name).collect { |t| [t.name,t.id]},{prompt: 'Select Team'},{class: 'form-control selectpicker show-tick dropup show-menu-arrow','data-actions-box': 'true','data-live-search': 'true' }%>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.label :project,class: 'label-class' %>
								<%= f.select :repo_id, [[]],{},{class: 'form-control selectpicker show-tick dropup show-menu-arrow','data-actions-box': 'true','data-live-search': 'true'}%>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.label :scan_type,class: 'label-class' %>
								<%= f.select :scan_type, options_for_select(AppConstants::AppTypes::APP_TYPES_WITH_VALUES),{prompt: 'Select Scan Type'},{:class=> "selectpicker dropup show-tick show-menu-arrow form-control",'data-live-search'=>"true"}%>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.label :tool,class: 'label-class' %>
								<%= f.select :source, options_for_select(AppConstants::TOOLS::EXTERNAL_TOOLS),{prompt: 'Select Tool'},{class: "form-control selectpicker dropup show-tick show-menu-arrow"}%>
							</div>
						</div>
						<div class="form-group" id="directory_field">
							<div class='col-md-6'>
								<!-- The fileinput-button span is used to style the file input field as button -->
								<%= f.label :upload_scan,"Upload Scan <a href='#' data-toggle='popover' data-trigger='hover' data-content='File format should be in xml' > <i class='glyphicon glyphicon-info-sign text-info'></i></a>".html_safe,class: 'label-class' %>
								<%= f.file_field :project_target,autofocus: true,required: 'required',class: "btn btn-success file-field" %>
							</div>
						</div>
						<div class="form-group ">
							<div class='col-md-4'>
								<%= f.submit "Upload Scan Results", :class=>"btn btn-danger"%>
							</div>
						</div>
					<%end%>
				</div>
			<%end%>
		</div>
	</div>
</div>
<script>
$('#scaners_team_id').change( function() { load_projects() });
</script>

web/app/app/views/upload_scans/index.html.erb
<div class="ts-main-content">
	<%=render "layouts/scaner_list"%>
	<div class="content-wrapper right-buffer">
		<div class="continer">
			<div id="message"></div>
		</div>	
		<div class="page-header">
			<%if params[:scan_type]== 'team'%>
				<%header = 'Team'%>
			<%elsif params[:scan_type] == 'corporate'%>
				<%header = 'Corporate'%>
			<%else%>
				<%header = 'My'%>
			<%end%>
			<h2><%=header%> Scans
				<%if current_user.is_admin? && params[:scan_type] == 'corporate'%>
					<span class='pull-right'> 
						<button class='btn btn-danger' onclick='start_scan_all_repos()'>Re-Scan/ Resume-scans</button>
					</span>
				<%end%>
			</h2>
		</div>          
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Project Title</th>
					<th>File Name</th>
					<th>Status</th>
					<th>Scan Results</th>
					<th>Delete</th>
				</tr>
			</thead>
			<tbody>         
				<%@scans.each do |scan| %>
					<tr id='<%=scan.id%>'>
						<%project_title = scan.project_title.present? ? scan.project_title : scan.repo.name%>
						<%findings = scan.findings.count%>
						<td><%= findings > 0 ? link_to(project_title,list_scan_results_scaners_path(scan_id: scan.id,scan_type: params[:scan_type].present? ? params[:scan_type] : "my_scans")) : project_title%></td>
						<td><%=scan.project_target_file_name%></td>
						<td><%=scan.status_reason.present? ? scan.status_reason : scan.status%></td>
						<td><%= link_to "Scan Results",uploaded_findings_findings_path(scan_id: scan.id,scan_type: params[:scan_type]) %></td>
						<td><%=link_to '<i class="glyphicon glyphicon-remove-circle text-danger"> </i>'.html_safe,scaner_path(scan),title: 'Delete',method: :delete, remote: true %> </td>
					</tr>
				<%end%> 
			</tbody>
		</table>
		<div class='text-center'> <%= will_paginate @scans ,renderer: BootstrapPagination::Rails%></div>
	</div>
</div>

web/app/app/views/upload_scans/new.html.erb
<%=render 'form'%>
<script type="text/javascript">
	$(".file-field").removeAttr("required");
</script>

web/app/app/views/upload_scans/uploaded_findings.html.erb
<div class="container">
	<div class="row">
		<ul class="breadcrumb">
			<%if session[:scan_type] == "my_scans"%>
				<li class="breadcrumb-item"><%=link_to "List Scan Targets",my_scans_scaners_path%></li>
			<%else%>
				<li class="breadcrumb-item"><%=link_to "List Scan Targets",scaners_path(scan_type: @scan_type)%></li>
			<%end%>
			<li class="breadcrumb-item active">Scan Results</li>
		</ul>
	</div>
	<div class='row'>
		<div class="panel panel-success target-stats">
			<div class="panel-heading"><b>Target Scan Stats</b> <a href="#" data-toggle="tooltip" title="No of Vulnerabilities" class='text-danger'>(<%=@findings.count%>)</a> </div>
			<div class='panel-body'>
				<div class='col-sm-3'>
					<div>
						<label class='label-class'>Application Name:</label> &nbsp
						<span><%=@scaner.project_title%></span>
					</div>
					<div>
						<label class='label-class'>Source:</label> &nbsp
						<span><%=@scaner.source%></span>                     
					</div>                                                                                      
				</div>
				<div class='col-sm-4'>
					<div>
						<label class='label-class'>Start Time:</label> &nbsp
						<%start_time = @scaner.start_time%>
						<span><%=start_time%></span>
					</div>
					<div>
						<label class='label-class'>End Time:</label> &nbsp
						<%end_time = @scaner.end_time%>
						<span><%=end_time%></span>
				</div>
				</div>
				<div class='col-sm-5'>
					<div>
						<label class='label-class'>Files Processed:</label> &nbsp
						<span><%=@scaner.no_of_processed_files%></span>
					</div>
					<div>
						<label class='label-class'>Application Languages:</label> &nbsp
						<span><%=@scaner.found_langs%></span>                     
					</div>                                                                                      
				</div>
				<div class='col-sm-10'>
					<label class='label-class'>Repository Path:</label> &nbsp       
					<span><%=@scaner.project_target_file_name%></span>                                    
				</div>
			</div>
		</div>
	</div>
	<div class='row top-buffer'>
		<div class="panel panel-success target-stats">
			<div class="panel-heading"><b>Scan Results</b> </div>
			<div class="panel-body">
				<table class="table borderless table-striped" id="findings_table" data-source="<%= findings_path(scan_id: @scaner.id,scan_type: params[:scan_type],format: "json") %>">
					<thead>
						<tr>
							<th>Severity</th>
							<th>Vulnerability Type</th>
							<%if current_user.is_admin?%>
								<th>Scanner</th>
							<%end%>
							<th>Issue In</th>
							<th>View Finding</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip();
	'<%if current_user.is_admin?%>'
			var target = [3,4];
	'<%else%>'
			var target = [2,3];

	'<%end%>'
	$('#findings_table').dataTable({               
		bServerSide: true,      
		order: [],      
		columnDefs: [ {
			targets  : target,
			orderable: false,
		}],  
		dom: 'BFlfrtip',
		buttons: [
		{
			extend:    'copyHtml5',
			text:      '<i class="fa fa-files-o"></i> Copy',
			titleAttr: 'Copy'
		},
		{
			extend:    'excelHtml5',
			text:      '<i class="fa fa-file-excel-o"></i> Excel',
			titleAttr: 'Excel'
		},
		{
			extend:    'csvHtml5',
			text:      '<i class="fa fa-file-text-o"></i> CSV',
			titleAttr: 'CSV'
		},
		{
			extend:    'pdfHtml5',
			text:      '<i class="fa fa-file-pdf-o"></i> PDF',
			titleAttr: 'PDF'
		}
		],
		sAjaxSource: $('#findings_table').data('source'),
		fnRowCallback: function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
			//$('td:eq(0)', nRow).addClass(aData[0].toLowerCase()+'-row').addClass('badge').addClass("finds-row");
		}
	});
});
//      var table = $('#findings_table').DataTables();
//      table.draw(false);
</script>