web/app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'
Rails.application.routes.draw do
	mount Sidekiq::Web => '/sidekiq'
	resources :tasks do
		collection do
			get 'tools_list'
			post 'update_tool'
			get 'configure_view'
			post 'update_configurations'
		end
	end
	resources :tags
	resources :permissions
	resources :functionalities
	devise_scope :user do
		root :to => 'users/sessions#new'
	end

	devise_for :users,controllers: {registrations: "users/registrations",omniauth_callbacks: "users/omniauth_callbacks"}
	resources :users do
		collection do
			get :autocomplete_user_name
			post :add
		end
	end
	resources :scaners do
		collection do
			get 'run'
			get 'load_projects'
			get 'load_branches'
			post 'store_bulk_scans'
			get 'list_scan_results'
			get 'severity_results'
			get 'scan_wise_results'
			get 'my_scans'
			get 'start_scan_for_all_repo'
			get 'add_dynamic_scans'
			get 'scans_diff'
			get 'run_truffle'
			get 'download_results'
			post 'change_find_status'
			get 'add_target'
			post 'unschedule'
		end
	end
	resources :findings do
		resources :comments
		resources :uploads do
			collection do 
				get 'download_file'
			end
		end
		resources :tags
		collection do
			get 'details'
			post 'change_status'
			post 'add_new_tag'
			post 'add_tag'
			delete 'delete_file'
			post 'change_false_positive'
			post 'publish_to_jira'
			post 'change_to_not_exploitable'
			get 'next_finding'
			post 'save_tag'
		end
	end
	resources :teams do
		collection do
			get 'fetch_projects'
			get 'list_groups'
			get 'repo_summary'
			get 'export_findings'
			get 'list_corpo_groups'
		end
	end
	resources :repos do
		collection do
			 get 'repo_summary'
			 get 'repo_tool_wise_findings'
			 get 'repo_severity_wise_findings'
			 get 'repo_channel_results'
			 get 'get_team_repos'
			 get 'list_apps'
			 get 'false_positive_finds'
			 delete 'delete_repo_channel_results'
		end
	end
	resources :dashboards do
		collection do
			get 'display'
			get 'static'
			get 'web'
			get 'wordpress'
			get 'mobile'
			get 'network'
		end
	end

	resource :settings do
		collection do
			get 'severity'
			get 'scanner'
			get 'jira'
			get 'gitlab'
			get 'github'
			get 'signup_role'
			get 'get_mail_info'
			get 'get_sender_mail'
			get 'pull_corporate_info'
			post 'update_details'
			post 'update_mail_info'
			post 'update_severities'
		end
	end	
	resources :user_management,:controller => :user_management
	resources :roles
	resources :groups
	resources :functionalities
	resources :analytics do
		collection do
			get :load_charts
			post :save_filters
			get :get_desc_wise
		end
	end
	resources :filters do
		collection do
			get :apply_filter
			post :results
		end
	end
	resources :scan_types
	resources :upload_scans do
		collection do
			post 'save_team'
		end
	end
	resources :alert_notifications do
		collection do
			post 'update_alerts'
		end
	end
	get 'restricted', :to=> 'errors#unauthorized'
	%w( 404 422 500 ).each do |code|
		get code, :to => "errors#show", :code => code
	end

end

web/app/app/models/task.rb
class Task < ActiveRecord::Base
	has_and_belongs_to_many :users,dependent: :destroy
	validates_uniqueness_of :name
	belongs_to :scan_type
end

web/app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:show, :edit, :update, :destroy]

	# GET /tasks
	# GET /tasks.json
	def index
		@list_scans_class = "/tasks"
		@tasks = Task.where.not(scan_type: nil).order(:group)
	end

	# GET /tasks/1
	# GET /tasks/1.json
	def show
	end

	# GET /tasks/new
	def new
		@list_scans_class = "/tasks/new"
		@task = Task.new
	end

	# GET /tasks/1/edit
	def edit
		@list_scans_class = "/tasks/#{params[:id]}/edit"
	end

	# POST /tasks
	# POST /tasks.json
	def create
		@task = Task.new(task_params)

		respond_to do |format|
			if @task.save
				format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
				format.json { render :show, status: :created, location: @task }
			else
				format.html { render :new }
				format.json { render json: @task.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /tasks/1
	# PATCH/PUT /tasks/1.json
	def update
		respond_to do |format|
			if @task.update(task_params)
				format.html { redirect_to tasks_url, notice: 'Task was successfully updated.' }
				format.json { render :show, status: :ok, location: @task }
			else
				format.html { render :edit }
				format.json { render json: @task.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /tasks/1
	# DELETE /tasks/1.json
	def destroy
		@list_scans_class = "/settings/scanner"
		@task.destroy
		respond_to do |format|
			format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
			format.json { head :no_content }
		end
	end
	def tools_list
		@list_scans_class = "/tasks/tools_list"
		@tasks = Task.where("scan_type_id is not NULL")
	end
	def update_tool
		@task = Task.find(params[:taks_id])
		if @task.gem_name.present?
			gems = @task.gem_name.split(",")
			gems.each do |gem|
				cmd = system("gem","update","#{gem}")
				if cmd == true
					@msg = "Upgradation successfully done."
					logger.info "#{gem} upgradation successfully done for #{gem}"
				else
					AlertNotification.create(user_id: current_user.id,identifier: 'tasks',alert_type: 'danger',message: "#{@task.name} upgradation is failed")
					logger.error "Some error happend while upgrading tool #{gem}"
					@msg = "Upgradation got failed."
				end
			end
		end
		respond_to do |format|
			format.js
		end
	end
	def configure_view
		@list_scans_class = '/tasks/configure_view'
		@commits_depth = Setting.pipeline['commits_depth']
		@commit_start_date = Setting.pipeline['commit_start_date']
		@regx_file = Dir.glob(File.join(Setting.pipeline["truffle_hog_path"],"regx_config_*")).select  {|f| File.file? f }.sort_by {|f| File.mtime f }.last
		@check_marx_server = Setting.pipeline['checkmarx_server']
		@check_marx_password = Setting.pipeline['checkmarx_password']
		@check_marx_user = Setting.pipeline['checkmarx_user']
		@check_marx_log = Setting.pipeline['checkmarx_log']
	end
	def update_configurations
		update_settings
                respond_to do |format|
                        flash[:notice] = "configurations updated successfully"
                        format.html { redirect_to :action=>"configure_view"}
                end
        end
	private
	# Use callbacks to share common setup or constraints between actions.
	def set_task
		@task = Task.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def task_params
		params.require(:task).permit(:name, :group, :scan_type_id,:gem_name)
	end
end

web/app/app/helpers/tasks_helper.rb
module TasksHelper
end

web/app/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
	<% if @task.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

			<ul>
				<% @task.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field form-group">
		<%= f.label :scan_type %>
		<%= f.select :scan_type_id, ScanType.all.collect{ |type| [type.name, type.id]},{},{class: "form-control",onchange: "enable_file_field();"}%>  
	</div>
	<div class="field form-group">
		<%= f.label :name %>
		<%= f.text_field :name,class: 'form-control' %>
	</div>
	<div class="field form-group">
		<%=f.label :group,"Supported Language" %>
		<%=f.select :group ,[["Ruby","Ruby"],["Java","Java"],["Javascript","Javascript"]],{prompt: 'Select Language'},{class: "form-control"}%>
	</div>
	<div class="field form-group">
		<label>
			Gem Name  <a href="#" data-toggle="popover" data-trigger="hover" font-size="8px;" data-content="Upgradation fails in case of incorrect gem name! .Add dependency gems with comma ',' separated">
				<i class='glyphicon glyphicon-info-sign text-info'></i>
			</a>  
		</label>
		<%= f.text_field :gem_name,class: 'form-control' %>
	</div>
	<div class="actions form-group">
		<%= f.submit "Update Tool",class: 'btn btn-primary'%>
	</div>
<% end %>

web/app/app/views/tasks/configure_view.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="container">    
			<div class="row">
				<ul class="breadcrumb">
					<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
					<li class="breadcrumb-item">Tools Configuration</li>
				</ul>
			</div>
			<div class='col-md-8'>
				<div class="panel-heading">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#secret_sesction">Hard Code Secret</a></li>
						<li><a data-toggle="tab" href="#checkmarx_section">Checkmarx</a></li>
					</ul>
				</div>
				<div class="tab-content top-buffer">
					<div id="secret_sesction" class="tab-pane fade in active">
						<%= form_for(:settings, url: update_configurations_tasks_path,:html=>{role: "form"}) do |form| %>
							<%= form.fields_for :pipeline do |f| %>    
								<div class="form-group">                                                                                                                                                                                            <%=f.label :commits_depth%>                                                                                                                                                                                 <%= f.number_field :commits_depth, autofocus: true,requred: true,class: "form-control",in: 1..50,value:  @commits_depth%>
							</div>                                                                                                                                                                                                      <div class="form-group " >
								<%=f.label :commit_start_date%>                                                                                                                                                                            <%= f.text_field :commit_start_date, autofocus: true,requred: true,class: "form-control",value: @commit_start_date%> 
							</div>
							<!--<div class="form-group " >
								<%#=f.label :commit_end_date%>
								<%#= f.text_field :commit_end_date, autofocus: true,requred: true,class: "form-control",value: @commits_date%>                              
							</div>--> 
							<div class="form-group input_fields_wrap" >
								<%=f.label :regx,"<button class='btn btn-primary regx'> <i class='glyphicon glyphicon-plus-sign'></i> Regx</button>".html_safe%>
								<%truffle_count = 1%>
								<%if @regx_file.present?%>
									<%File.open(@regx_file,"r").each_line do |line|%>
										<div class="input-group control-group after-add-more top-buffer">
											<%buffer_class = truffle_count == 1 ? "" : "top-buffer"%>
											<%=f.text_area "truffle_regx_#{truffle_count}".to_sym, autofocus: true,requred: true,class: "form-control #{buffer_class}",value: line,style:"width: 737px; height: 63px;" ,readonly: true%>
											<div class="input-group-btn"> 
												<a class="btn remove_field" title="Remove field"> 
													<i class="glyphicon glyphicon-remove-circle text-danger" title='Remove'></i>
												</a>
												<a class="btn edit_field" title="Remove field" value="truffle_regx_<%=truffle_count%>">
													<i class="glyphicon glyphicon-edit text-primary" title='Edit'></i>
												</a>
											</div>
											<%truffle_count += 1%>
										</div>
									<%end%>
								<%end%>
							</div>
							<div class="form-group" >
								<%= f.submit "Save",class: 'btn btn-danger'%>             
								&nbsp;&nbsp; <a href="#" data-toggle="popover" data-trigger="hover" font-size="8px;" data-content="if no of commits are less than configured date, system will take confgured date">
									<i class='glyphicon glyphicon-info-sign text-info'></i>
								</a>
							</div>
						<%end%>
					<%end%>
					</div>

					<div id="checkmarx_section" class="tab-pane fade">
						<%= form_for(:settings, url: update_configurations_tasks_path ,:html=>{role: "form"}) do |form| %>
							<%= form.fields_for :pipeline do |f| %> 
								<div class="form-group">
									<%=f.label :server%>
									<%= f.text_field :checkmarx_server, autofocus: true,requred: true,class: "form-control",value:  @check_marx_server%>
								</div>
								<div class="form-group " >
									<%=f.label :user_name%>
									<%= f.text_field :checkmarx_user, autofocus: true,requred: true,class: "form-control",value: @check_marx_user%>
								</div>                                          
								<div class="form-group " >
									<%=f.label :password%>
									<%= f.password_field :checkmarx_password, autofocus: true,requred: true, class: "form-control",value: @check_marx_password %>
								</div>                                                                 
								<div class="form-group " >
									<%=f.label :checkmarx_log_file%>
									<%= f.text_field :checkmarx_log, autofocus: true,requred: true, class: "form-control",value: @check_marx_log %>
								</div>
								<div class="form-group" >                                                           
									<%= f.submit "Save",class: 'btn btn-danger'%>                                        
								</div>   
							<%end%>
						<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<script>
$(document).ready(function(){
	$('#settings_pipeline_commit_start_date').datetimepicker({format: 'DD-MM-YYYY'});
	$('#settings_pipeline_commit_end_date').datetimepicker({format: 'DD-MM-YYYY'});
	var max_fields      = 5; 
	var wrapper         = $(".input_fields_wrap");
	var add_button      = $(".regx"); //Add button ID
	var x = $('textarea').length; //initlal text box count
	$(add_button).click(function(e){ //on add input button click
		e.preventDefault();
		if(x < max_fields){ //max input box allowed
			x++; //text box increment
			$(wrapper).append('<div class="input-group control-group after-add-more top-buffer" ><textarea  id="settings_pipeline_truffle_regx_'+x+'" style="width: 737px; height: 63px;" class="form-control" name="settings[pipeline][truffle_regx_'+x+']"/><div class="input-group-btn"> <a class="btn remove_field" title="Remove field"> <i class="glyphicon glyphicon-remove-circle text-danger"></i></a><a class="btn edit_field" title="Remove field"><i class="glyphicon glyphicon-edit text-primary"></i></a></div></div>'); //add input box
		}
	});

	$(wrapper).on("click",".remove_field",function(e){ //user click on remove text
		e.preventDefault(); 
		$(this).closest('.after-add-more').remove(); 
		x--;
		var no_of_regx = $('textarea').length;
		$("textarea").each(function(index){
			var teaxt_area_index = index + 1;
			$(this).attr("id","settings_pipeline_truffle_regx_"+teaxt_area_index);
			$(this).attr("name","settings[pipeline][truffle_regx_"+teaxt_area_index+"]")
		 })
	})
	$(wrapper).on("click",".edit_field",function(e){ //user click on remove text
		e.preventDefault();
		$("#settings_pipeline_" + $(this).attr("value")).attr("readonly",false);
	})
});
</script>

web/app/app/views/tasks/edit.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class='container'>
			<ul class="breadcrumb">
				<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
				<li class="breadcrumb-item active"><%= link_to "Enable/ Disable Tools",scanner_settings_path%></li>
				<li class="breadcrumb-item active"><%= link_to "Tools list",tasks_path%></li>
				<li class="breadcrumb-item">Editing Tool</li>
			</ul>
			<div class='row'>
				<div class='col-md-8'>
					<div class="panel panel-default">
						<div class="panel-heading"><h4>Editing Tool</h4></div>
						<div class="panel-body">
							<%= render 'form' %>
							<%= link_to 'Back', tasks_path %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

web/app/app/views/tasks/index.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class='container'>
			<div class="row">
				<ul class="breadcrumb">
					<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
					<li class="breadcrumb-item active"><%= link_to "Enable/ Disable Tools",scanner_settings_path%></li>
					<li class="breadcrumb-item">Listing Tools</li>
				</ul>   
			</div>  
			<div class='row'>
				<div class="panel panel-default">
					<div class="panel-heading"><h4>Listing Tools</h4></div>
					<div class="panel-body">

						<table class='table'>
							<thead>
								<tr>
									<th>Name</th>
									<th>Supported Language</th>
									<th>Scan type</th>
									<th>Edit</th>
									<th>Delete</th>
								</tr>
							</thead>

							<tbody>
								<% @tasks.each do |task| %>
									<tr>
										<td><%= task.name %></td>
										<td><%= task.group %></td>
										<td><%= task.scan_type.name %></td>
										<td><%= link_to '<i class="fa fa-pencil-square-o"> </i>'.html_safe, edit_task_path(task) %></td>
										<td><%= link_to '<i class="glyphicon glyphicon-remove-circle text-danger"> </i>'.html_safe, task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						<%= link_to 'New Task', new_task_path %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

web/app/app/views/tasks/new.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper">
		<div class="container">
			<div id="settings_message"></div>
			<ul class="breadcrumb">
				<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
				<li class="breadcrumb-item active"><%= link_to "Enable/ Disable Tools",scanner_settings_path%></li>
				<li class="breadcrumb-item">New Tool</li>
			</ul>
			<div class='row'>
				<div class='col-md-8'>
					<div class="panel panel-default">
						<div class="panel-heading"><h4>New Tool</h4></div>
						<div class="panel-body">

							<%= render 'form' %>

							<%= link_to 'Back', tasks_path %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

web/app/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @task.group %>
</p>

<p>
  <strong>Scan type:</strong>
  <%= @task.scan_type %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

web/app/app/views/tasks/tools_list.html.erb
<div class="ts-main-content">
	<%=render "layouts/user_settings"%>
	<div class="content-wrapper" id="upgrade_section">
		<div class='container'>
			<div class="row">
				<ul class="breadcrumb">                                                                                                                 
					<li class="breadcrumb-item active"><%= link_to "User Settings",scan_types_path%></li>
					<li class="breadcrumb-item">Upgrade Tools</li>
				</ul>   
			</div>  
			<div class='row'>
				<div class="panel panel-default">
					<div class="panel-heading"><h4>Listing Tasks</h4></div>
					<div class="panel-body">

						<table class='table'>
							<thead>
								<tr>
									<th>Name</th>
									<th>Supported Language</th>
									<th>Upgrade</th>
									<th>Steps to upgrade</th>
								</tr>
							</thead>

							<tbody>
								<% @tasks.each do |task| %>
									<%if task.scan_type_id.present?%>
										<tr>
											<td><%= task.name %></td>
											<td><%= task.group %></td>
											<td><%=link_to "Upgrade",update_tool_tasks_path(taks_id: task.id),class: 'btn btn-danger',title:'Upgrade',method: :post,remote: true,onclick: 'add_spinner()' if task.is_direct_upgrade%></td>

											<td>
												<%if task.is_custom == false && task.is_direct_upgrade == false%>
													<button type="button" class="btn btn-info" data-toggle="modal" data-target="#<%=task.name%>">Steps To Upgrade</button>
												<%end%>
											</td>
										</tr>
									<%end%>
								<% end %>
							</tbody>
						</table>
						<%= link_to 'New Task', new_task_path %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--Xanitizer Modal -->
<div class="modal fade" id="Xanitizer" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Xanitizer upgradation steps</h4>
			</div>
			<div class="modal-body">
				<p>Step 1: Go to <a href="https://www.rigs-it.net/opendownloads/mrkoasewk-Xanitizer-3.1/downloadLinux.html" target="_blank">Xanitizer download link</a></p>
				<p>Step 2: Click on download link</p>
				<p>Step 3: Delete existing Xanitizer version from directory jackhammer/web/app/tools/</p>
				<p>Step 4: please untar downloaded file and copy to jackhammer/web/app/tools/</p>
				<p class='text-center'> ----------------Upgradation is done !-------------</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
<!--findgsecbugs Modal -->
<div class="modal fade" id="FindSecurityBugs" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Findsecbugs upgradation steps</h4>
			</div>
			<div class="modal-body">
				<p>Step 1: Go to <a href="https://github.com/find-sec-bugs/find-sec-bugs/releases" target="_blank">Findsecbugs download link</a></p>
				<p>Step 2: Find latest findsecbugs-cli zip file  and download it</p>
				<p>Step 3: Delete existing findsecbugs-cli version from directory jackhammer/web/app/tools/</p>
				<p>Step 4: please untar downloaded file and copy to jackhammer/web/app/tools/</p>
				<p class='text-center'> ----------------Upgradation is done !-------------</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="PMD" role="dialog">
        <div class="modal-dialog">
                <div class="modal-content">
                        <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">PMD upgradation steps</h4>
                        </div>
                        <div class="modal-body">
                                <p>Step 1: Go to <a href="https://pmd.github.io/" target="_blank">PMD download link</a></p>
                                <p>Step 2: Click on latest vesion and click on downloads</p>
                                <p>Step 3: Delete existing findsecbugs-cli version from directory jackhammer/web/app/tools/</p>
                                <p>Step 4: please untar downloaded file and copy to jackhammer/web/app/tools/</p>
                                <p class='text-center'> ----------------Upgradation is done !-------------</p>
                        </div>
                        <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                </div>
        </div>
</div>

<script>
function add_spinner()
{
	$("body").spin({
		lines: 12, // The number of lines to draw
		length: 7, // The length of each line
		width: 9, // The line thickness
		radius: 30, // The radius of the inner circle
		color: '#000', // #rgb or #rrggbb
		speed: 1, // Rounds per second
		trail: 60, // Afterglow percentage
		shadow: false // Whether to render a shadow
	});
}
</script>

web/app/app/views/tasks/update_tool.js.erb
$("body").spin(false);
alert('<%=@msg%>');